#!/bin/bash
# To be ran from repo root folder
make stage
pkill -9 beam.smp; LDB_PORT=6717 _build/default/rel/ldb/bin/ldb start
rm -rf ldb-java-client/
git clone https://github.com/vitorenesduarte/ldb-java-client
cd ldb-java-client
mvn -q test
